version: '3'

services:
  # Mysql db
  task-manager-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TaskManagerDb
      - MYSQL_USER=ezequiel
      - MYSQL_PASSWORD=ezequiel
    ports:
      - 3306:3306

  # Frontend Service
  task-manager-backend:
    image: xeitor/task-manager-spring
    restart: on-failure
    depends_on:
      - task-manager-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=task-manager-mysql
      - DATABASE_USER=ezequiel
      - DATABASE_PASSWORD=ezequiel
      - DATABASE_NAME=TaskManagerDb
      - DATABASE_PORT=3306
  # Frontend Service
  task-manager-frontend:
    image: task-manager-react
    ports:
      - "3000:3000"
    restart: always
